name: Semgrep Diff Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: master

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep differential scan
        run: semgrep ci --config auto --oss-only --dataflow-traces --text --text-output=semgrep_diffscan.txt --sarif-output=semgrep_diffscan.sarif --severity=WARNING --severity=ERROR

      - name: Upload reports
        uses: actions/upload-artifact@master
        with:
           name: ${{ github.event.repository.name }} Semgrep Diffscan report
           path: ${{github.workspace}}/semgrep_diffscan.*
