# Name of this GitHub Actions workflow.
name: Semgrep Full Scan

on:
  workflow_dispatch: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  semgrep:
    name: semgrep/scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4

      - name: Create Status Check
        id: create_check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            CHECKID=$(curl -L -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GH_TOKEN"\
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ github.repository }}/check-runs \
             -d '{"name":"Semgrep Status Check", "head_sha":"${{ github.event.pull_request.head.sha }}", "status":"in_progress","output":{"title":"Semgrep scan results", "summary":"Waiting for Semgrep scanner to run"}}' \
             | jq '.id')

             echo "check_id=$CHECKID" >> $GITHUB_OUTPUT

      - name: Run Semgrep fullscan
        run: semgrep scan --config auto --oss-only --dataflow-traces -q --text --json-output=semgrep_fullscan.json --vim-output=semgrep_fullscan.txt --severity=WARNING --severity=ERROR .

      - name: Fail Status Check (scan failed)
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ github.token }}
          CHECK_ID: ${{ steps.create_check.outputs.check_id }}
        run: |
            curl -L -X PATCH \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GH_TOKEN"\
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_ID \
             -d '{"name":"Semgrep Status Check", "head_sha":"${{ github.event.pull_request.head.sha }}", "conclusion":"failure","output":{"title":"Semgrep scan results", "summary":"Semgrep scanner failed to run!"}}'    
      
      - name: Get count of issues
        if: ${{ hashFiles('semgrep_fullscan.json') != '' }}
        run: |
            echo "high_severity=$(cat semgrep_fullscan.json | jq '.results[].extra | select(.severity == "ERROR")' | jq --slurp '.' | jq length)" >> $GITHUB_OUTPUT
            echo "total=$(cat semgrep_fullscan.json | jq '.results | length')" >> $GITHUB_OUTPUT
        id: issues_count
     
      - name: Fail Status Check (severe vuns)
        if: ${{ hashFiles('semgrep_fullscan.json') != '' && steps.issues_count.outputs.high_severity > 0}}
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUES_COUNT: ${{ steps.issues_count.outputs.total }}
          CHECK_ID: ${{ steps.create_check.outputs.check_id }}
        run: |
            curl -L -X PATCH \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GH_TOKEN"\
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_ID \
             -d '{"name":"Semgrep Status Check", "head_sha":"${{ github.event.pull_request.head.sha }}", "conclusion":"failure","output":{"title":"Semgrep scan results", "summary":"Semgrep scanner has found '$ISSUES_COUNT' severe vulnerabilities!", "text": "'"$(awk '{gsub(/'\''/, "'\''\\\\'\'\''");gsub(/"/, "\\\""); printf "%s\\n\\n", $0}' semgrep_fullscan.txt)"'","annotations":[{"annotation_level": "error", "start_line": "12", "end_line": "12", "path": "vulnerabilities/brute/source/low.php", "title": "php.lang.security.injection.tainted-sql-string.tainted-sql-string", "message": "User data flows into this manually-constructed SQL string. User data can be safely inserted into SQL strings using prepared statements or an object-relational mapper (ORM). Manually-constructed SQL strings is a possible indicator of SQL injection, which could let an attacker steal or manipulate data from the database. Instead, use prepared statements (`$mysqli->prepare(\"INSERT INTO test(id, label) VALUES (?, ?)\");`) or a safe library."}]}}'    
