name: Run Trufflehog scan

on:
  workflow_dispatch: 
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
