name: TruffleHog Full Scan

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 15 * * 2"

jobs:
  trufflehog:
    name: trufflehog/scan
    runs-on: ubuntu-latest
    container:
      image: trufflesecurity/trufflehog
    steps:
      - uses: actions/checkout@v4

      - name: Run TruffleHog fullscan
        run: trufflehog filesystem . --no-fail | tee trufflehog_fullscan.txt
      
      - name: Upload reports
        uses: actions/upload-artifact@master
        with:
           name: ${{ github.event.repository.name }} TruffleHog Fullscan report
           path: ${{github.workspace}}/trufflehog_fullscan.*
